from decimal import Decimal

from sqlalchemy import select
from sqlalchemy.orm import Session

from app.finance.models import FinanceProduct

DATASET_VERSION = "qian-v1"
DATA_UPDATED_AT = "2026-08-23"


def _p(code: str, name: str, inst: str, cat: str, scenario: str,
       min_amt: int, max_amt: int, min_d: int, max_d: int,
       rate: str, fee: str, purposes: list[str], guarantees: list[str],
       creds: list[str], min_years: str, reqs: list[str]) -> dict:
    return {
        "product_code": code, "name": name, "institution_name": inst,
        "category": cat, "scenario": scenario,
        "min_amount_yuan": Decimal(min_amt), "max_amount_yuan": Decimal(max_amt),
        "min_days": min_d, "max_days": max_d,
        "annual_rate_pct": Decimal(rate), "fee_note": fee,
        "purposes": purposes, "guarantee_modes": guarantees,
        "required_credentials": creds, "min_business_years": Decimal(min_years),
        "requirements": reqs, "data_updated_at": DATA_UPDATED_AT,
        "dataset_version": DATASET_VERSION, "is_active": True,
    }


_PUR = ["grain_purchase"]
_INV = ["inventory_turnover"]
_RCV = ["receivable_turnover"]

PRODUCTS = [
    # ── 采购周转融资 purchase_working × 15 ────────────────────────────────
    _p("QIAN-V1-PW-01", "粮采周转贷", "谷穗金融服务中心", "purchase_working",
       "粮食采购周转资金短期周转", 100_000, 1_000_000, 15, 90, "5.200",
       "无额外服务费，提前还款无违约金", _PUR, ["credit", "guarantee"], ["purchase_contract"], "1.0",
       ["企业持续经营满1年", "具有真实粮食采购合同", "经营与征信情况需人工核验"]),
    _p("QIAN-V1-PW-02", "小额采购快融", "惠粮产业服务", "purchase_working",
       "小额粮食采购快速融资", 50_000, 500_000, 7, 60, "7.200",
       "审批快速，无额外服务费", _PUR, ["credit"], ["purchase_contract"], "0.5",
       ["企业持续经营满半年", "具有真实粮食采购合同", "经营情况需人工核验"]),
    _p("QIAN-V1-PW-03", "粮企经营贷", "启禾普惠服务", "purchase_working",
       "粮食企业经营周转资金", 200_000, 2_000_000, 90, 365, "6.800",
       "中长期经营周转，利率按实际期限折算", _PUR, ["credit", "guarantee"], ["business_license", "bank_flow"], "2.0",
       ["企业持续经营满2年", "具备营业执照与银行流水", "经营与征信情况需人工核验"]),
    _p("QIAN-V1-PW-04", "季采备货贷", "丰收金融服务中心", "purchase_working",
       "季节性粮食集中采购备货", 300_000, 3_000_000, 30, 120, "5.500",
       "季节性产品，秋收期间可申请延期", _PUR, ["credit", "guarantee"], ["purchase_contract"], "1.5",
       ["企业持续经营满1.5年", "具有真实粮食采购合同", "征信记录需人工审核"]),
    _p("QIAN-V1-PW-05", "快审采购通", "捷融普惠平台", "purchase_working",
       "线上快审粮食采购融资", 30_000, 300_000, 7, 45, "7.800",
       "全程线上审批，最快当日到账", _PUR, ["credit"], ["purchase_contract"], "0.5",
       ["企业持续经营满半年", "具有真实采购合同", "法人身份信息需线上验证"]),
    _p("QIAN-V1-PW-06", "联营周转金", "合穗产业金融", "purchase_working",
       "联营模式下的采购周转", 150_000, 1_500_000, 30, 150, "5.900",
       "联营企业互保，利率优惠", _PUR, ["guarantee"], ["purchase_contract", "business_license"], "1.0",
       ["企业持续经营满1年", "需提供联营方资质材料", "经营情况需人工核验"]),
    _p("QIAN-V1-PW-07", "散收快融贷", "惠农金融服务", "purchase_working",
       "零散粮食收购快速融资", 20_000, 200_000, 5, 30, "8.000",
       "小额高频，适合散收场景", _PUR, ["credit"], ["purchase_contract"], "0.5",
       ["企业持续经营满半年", "具有真实收购凭证", "经营情况需人工核验"]),
    _p("QIAN-V1-PW-08", "产区直采贷", "谷源供应链金融", "purchase_working",
       "产区直接采购专项融资", 500_000, 5_000_000, 30, 180, "5.000",
       "产区直采专项，利率较低", _PUR, ["credit", "guarantee"], ["purchase_contract", "bank_flow"], "2.0",
       ["企业持续经营满2年", "具有产区采购合同与银行流水", "经营与征信需人工核验"]),
    _p("QIAN-V1-PW-09", "批发采购通", "粮商金融服务中心", "purchase_working",
       "批发市场大宗采购融资", 200_000, 2_000_000, 15, 90, "6.200",
       "批发市场驻场服务，审批便捷", _PUR, ["credit", "order"], ["purchase_contract"], "1.0",
       ["企业持续经营满1年", "具有批发市场交易凭证", "经营情况需人工核验"]),
    _p("QIAN-V1-PW-10", "绿色粮食贷", "绿穗生态金融", "purchase_working",
       "绿色有机粮食采购专项", 100_000, 800_000, 30, 120, "5.300",
       "绿色有机认证企业可享优惠利率", _PUR, ["credit"], ["purchase_contract", "business_license"], "1.5",
       ["企业持续经营满1.5年", "需持有绿色或有机认证", "征信情况需人工核验"]),
    _p("QIAN-V1-PW-11", "跨省调运贷", "通达产业金融", "purchase_working",
       "跨省粮食调运采购融资", 300_000, 3_000_000, 30, 90, "5.700",
       "支持跨省采购与物流联动", _PUR, ["guarantee"], ["purchase_contract"], "1.0",
       ["企业持续经营满1年", "具有跨省采购合同", "物流合作方需确认"]),
    _p("QIAN-V1-PW-12", "合作社采购融", "禾联互助金融", "purchase_working",
       "农业合作社联合采购融资", 50_000, 600_000, 15, 90, "6.500",
       "合作社成员互保模式", _PUR, ["guarantee", "credit"], ["purchase_contract"], "1.0",
       ["合作社持续经营满1年", "具有真实采购合同", "需提供合作社登记证明"]),
    _p("QIAN-V1-PW-13", "应急周转金", "速粮金融应急服务", "purchase_working",
       "突发采购资金应急周转", 30_000, 200_000, 3, 15, "9.200",
       "应急通道，利率较高但放款极快", _PUR, ["credit"], ["purchase_contract"], "0.5",
       ["企业持续经营满半年", "具有紧急采购证明", "法人身份需线上核验"]),
    _p("QIAN-V1-PW-14", "储备采购贷", "国穗储备金融服务", "purchase_working",
       "粮食储备轮入采购融资", 500_000, 8_000_000, 60, 180, "4.800",
       "储备轮入专项，利率优惠", _PUR, ["credit", "guarantee"], ["purchase_contract", "business_license"], "3.0",
       ["企业持续经营满3年", "具有储备轮入批文", "征信与经营状况需人工核验"]),
    _p("QIAN-V1-PW-15", "进口粮食融", "远洋供应链金融", "purchase_working",
       "进口粮食采购融资", 1_000_000, 10_000_000, 30, 180, "5.400",
       "进口粮食专项，支持信用证结算", _PUR, ["credit", "order"], ["purchase_contract", "bank_flow"], "2.0",
       ["企业持续经营满2年", "具有进口合同与信用证", "外汇与征信需人工核验"]),

    # ── 订单融资 order_finance × 15 ─────────────────────────────────────
    _p("QIAN-V1-OF-01", "订单采购融", "丰融供应链服务", "order_finance",
       "基于采购订单的粮食融资", 200_000, 3_000_000, 30, 180, "5.800",
       "基于真实订单，利率参考市场行情", _PUR, ["order", "guarantee"], ["purchase_contract", "purchase_order"], "1.0",
       ["企业持续经营满1年", "具有真实采购合同与采购订单", "经营与征信情况需人工核验"]),
    _p("QIAN-V1-OF-02", "采购合同快融", "衡信产业金融服务", "order_finance",
       "采购合同项下快速融资", 100_000, 1_500_000, 30, 120, "6.300",
       "无额外担保费用，信用+订单双覆盖", _PUR, ["order", "credit"], ["purchase_contract"], "1.0",
       ["企业持续经营满1年", "具有真实粮食采购合同", "经营与征信情况需人工核验"]),
    _p("QIAN-V1-OF-03", "联保采购融", "谷链产业服务", "order_finance",
       "联保模式下的粮食采购融资", 300_000, 2_000_000, 30, 180, "5.900",
       "联保模式，利率相对优惠", _PUR, ["guarantee"], ["purchase_contract"], "1.5",
       ["企业持续经营满1.5年", "具有真实粮食采购合同", "需提供联保方资质材料"]),
    _p("QIAN-V1-OF-04", "中标订单融", "政穗金融服务", "order_finance",
       "政府中标采购订单融资", 200_000, 5_000_000, 30, 180, "5.200",
       "政府采购中标订单专项", _PUR, ["order"], ["purchase_contract", "purchase_order"], "1.0",
       ["企业持续经营满1年", "具有政府采购中标通知书", "采购合同需人工核验"]),
    _p("QIAN-V1-OF-05", "核心企业订单融", "联禾订单金融", "order_finance",
       "核心粮食企业下游订单融资", 500_000, 5_000_000, 60, 270, "5.000",
       "核心企业信用传导，利率优惠", _PUR, ["order", "credit"], ["purchase_contract", "purchase_order"], "1.5",
       ["企业持续经营满1.5年", "核心企业需为行业前列", "订单真实性需人工核验"]),
    _p("QIAN-V1-OF-06", "预付款融资", "先禾金融服务", "order_finance",
       "粮食采购预付款专项融资", 100_000, 1_000_000, 15, 60, "6.800",
       "解决预付款资金压力", _PUR, ["order", "guarantee"], ["purchase_contract"], "1.0",
       ["企业持续经营满1年", "具有预付款条款的采购合同", "供应方资质需核验"]),
    _p("QIAN-V1-OF-07", "长期协议融", "稳穗产业金融", "order_finance",
       "长期采购协议项下循环融资", 500_000, 8_000_000, 180, 365, "5.300",
       "长期协议循环额度，利率较低", _PUR, ["order", "credit"], ["purchase_contract", "purchase_order", "bank_flow"], "2.0",
       ["企业持续经营满2年", "具有12个月以上采购协议", "银行流水需连续6个月"]),
    _p("QIAN-V1-OF-08", "竞价采购融", "拍卖金融快线", "order_finance",
       "粮食竞价交易采购融资", 200_000, 3_000_000, 7, 60, "6.500",
       "竞价拍卖场景快速放款", _PUR, ["order"], ["purchase_contract", "purchase_order"], "1.0",
       ["企业持续经营满1年", "具有拍卖成交确认书", "保证金需提前缴纳"]),
    _p("QIAN-V1-OF-09", "进口订单融", "海穗供应链金融", "order_finance",
       "进口粮食订单专项融资", 500_000, 8_000_000, 60, 180, "5.500",
       "进口粮食订单专项，支持外币结算", _PUR, ["order", "guarantee"], ["purchase_contract", "purchase_order"], "2.0",
       ["企业持续经营满2年", "具有进口粮食采购订单", "外汇资质需核验"]),
    _p("QIAN-V1-OF-10", "电商订单融", "云粮电商金融", "order_finance",
       "电商平台粮食订单融资", 50_000, 500_000, 15, 90, "7.000",
       "电商平台数据授信，线上放款", _PUR, ["order", "credit"], ["purchase_order"], "0.5",
       ["电商店铺经营满半年", "具有平台订单数据", "平台信用评级需达标"]),
    _p("QIAN-V1-OF-11", "季节性订单贷", "时令金融服务", "order_finance",
       "季节性粮食订单集中采购", 300_000, 3_000_000, 30, 120, "5.600",
       "秋收/春播季节专项额度", _PUR, ["order", "guarantee"], ["purchase_contract", "purchase_order"], "1.0",
       ["企业持续经营满1年", "具有季节性采购订单", "经营情况需人工核验"]),
    _p("QIAN-V1-OF-12", "深加工订单融", "穗加工产业金融", "order_finance",
       "粮食深加工企业原料订单融资", 500_000, 5_000_000, 60, 180, "5.700",
       "深加工企业原料采购专项", _PUR, ["order", "credit"], ["purchase_contract", "purchase_order"], "2.0",
       ["企业持续经营满2年", "具有加工许可与订单", "加工产能需核验"]),
    _p("QIAN-V1-OF-13", "饲料订单融", "牧穗金融服务", "order_finance",
       "饲料企业粮食原料采购融资", 200_000, 3_000_000, 30, 120, "6.000",
       "饲料企业原料采购专项", _PUR, ["order", "guarantee"], ["purchase_contract"], "1.0",
       ["企业持续经营满1年", "具有饲料生产许可", "采购合同需人工核验"]),
    _p("QIAN-V1-OF-14", "酒企原料融", "酒穗供应链金融", "order_finance",
       "酿酒企业粮食原料采购融资", 300_000, 5_000_000, 60, 180, "5.400",
       "酿酒企业高粱、小麦等原料专项", _PUR, ["order", "credit"], ["purchase_contract", "purchase_order"], "2.0",
       ["企业持续经营满2年", "具有酿酒许可与采购合同", "品质要求需核验"]),
    _p("QIAN-V1-OF-15", "集团统采融", "集穗产业金融", "order_finance",
       "集团企业统一采购融资", 1_000_000, 15_000_000, 60, 270, "4.800",
       "集团统一采购，批量利率优惠", _PUR, ["order", "guarantee", "credit"], ["purchase_contract", "purchase_order", "bank_flow"], "3.0",
       ["集团持续经营满3年", "具有集团统采协议", "集团财务需人工核验"]),

    # ── 仓单/货权融资 warehouse_finance × 10 ──────────────────────────────
    _p("QIAN-V1-WH-01", "粮仓快融", "丰仓供应链服务", "warehouse_finance",
       "仓单质押快速融资", 500_000, 5_000_000, 30, 365, "4.900",
       "仓单质押，利率较低；需仓储监管方配合", _INV, ["warehouse_receipt"], ["warehouse_receipt"], "1.0",
       ["企业持续经营满1年", "具有合规仓单", "仓储监管方需确认货权清晰"]),
    _p("QIAN-V1-WH-02", "货权周转融", "粮链金融服务", "warehouse_finance",
       "受控货权项下资金周转", 1_000_000, 8_000_000, 60, 365, "5.100",
       "受控货权模式，适合大宗粮食周转", _INV, ["controlled_goods"], ["controlled_goods"], "2.0",
       ["企业持续经营满2年", "货权清晰且受监管方控制", "经营与征信情况需人工核验"]),
    _p("QIAN-V1-WH-03", "标准仓单融", "国标仓单金融服务", "warehouse_finance",
       "标准仓单质押融资", 800_000, 10_000_000, 30, 365, "4.500",
       "标准仓单质押，利率最优惠", _INV, ["warehouse_receipt"], ["warehouse_receipt"], "1.5",
       ["企业持续经营满1.5年", "仓单须为国标交割仓单", "仓库须为指定交割库"]),
    _p("QIAN-V1-WH-04", "临储质押融", "储穗金融服务", "warehouse_finance",
       "临储粮食质押融资", 300_000, 3_000_000, 30, 180, "5.300",
       "临储粮食质押，适合中小粮企", _INV, ["warehouse_receipt"], ["warehouse_receipt"], "1.0",
       ["企业持续经营满1年", "临储粮食须存储在认可仓库", "仓储合同需核验"]),
    _p("QIAN-V1-WH-05", "电子仓单融", "数字粮仓金融", "warehouse_finance",
       "电子仓单线上质押融资", 500_000, 5_000_000, 15, 180, "4.800",
       "电子仓单全线上操作，效率高", _INV, ["warehouse_receipt"], ["warehouse_receipt"], "1.0",
       ["企业持续经营满1年", "须接入电子仓单系统", "仓储数据需实时对接"]),
    _p("QIAN-V1-WH-06", "冷库质押融", "冷链金融服务", "warehouse_finance",
       "冷库粮食质押融资", 200_000, 2_000_000, 30, 180, "5.600",
       "冷链仓储质押，适合需温控的粮食品种", _INV, ["warehouse_receipt"], ["warehouse_receipt"], "1.0",
       ["企业持续经营满1年", "粮食须存储在合规冷库", "温控记录需核验"]),
    _p("QIAN-V1-WH-07", "港口货权融", "港穗物流金融", "warehouse_finance",
       "港口存货货权质押融资", 1_000_000, 10_000_000, 30, 180, "5.000",
       "港口存货质押，适合进出口粮食", _INV, ["controlled_goods"], ["controlled_goods"], "2.0",
       ["企业持续经营满2年", "货物须在港口监管区", "海关单据需核验"]),
    _p("QIAN-V1-WH-08", "产区仓储融", "产穗仓储金融", "warehouse_finance",
       "产区仓储粮食质押融资", 300_000, 3_000_000, 30, 270, "5.400",
       "产区仓储质押，适合收储企业", _INV, ["warehouse_receipt"], ["warehouse_receipt"], "1.0",
       ["企业持续经营满1年", "仓储设施须符合标准", "库存盘点需配合"]),
    _p("QIAN-V1-WH-09", "动态库存融", "流动仓储金融", "warehouse_finance",
       "动态库存监管质押融资", 500_000, 5_000_000, 60, 365, "5.200",
       "动态库存监管，允许部分出入库", _INV, ["controlled_goods"], ["controlled_goods"], "1.5",
       ["企业持续经营满1.5年", "须接入库存监管系统", "最低库存量需保证"]),
    _p("QIAN-V1-WH-10", "联合仓单融", "联仓金融服务", "warehouse_finance",
       "多家企业联合仓单融资", 200_000, 2_000_000, 30, 180, "5.500",
       "联合仓单模式，适合中小粮企集合融资", _INV, ["warehouse_receipt", "guarantee"], ["warehouse_receipt"], "1.0",
       ["企业持续经营满1年", "须加入联合仓单计划", "联保方资质需核验"]),

    # ── 应收账款融资 receivable_finance × 10 ──────────────────────────────
    _p("QIAN-V1-AR-01", "应收速融", "商穗保理服务", "receivable_finance",
       "应收账款快速保理融资", 300_000, 3_000_000, 30, 180, "6.100",
       "保理融资，按实际回款周期计费", _RCV, ["receivable"], ["receivable_invoice"], "1.0",
       ["企业持续经营满1年", "具有真实应收账款凭证", "交易对手方需具备合理信用资质"]),
    _p("QIAN-V1-AR-02", "核心企业应收融", "联禾商业保理", "receivable_finance",
       "核心企业应收账款专项保理", 500_000, 5_000_000, 30, 270, "5.600",
       "核心企业应收专项，利率相对优惠", _RCV, ["receivable"], ["receivable_invoice", "delivery_receipt"], "1.5",
       ["企业持续经营满1.5年", "具有真实应收账款凭证与交货单", "交易对手须为粮食核心企业"]),
    _p("QIAN-V1-AR-03", "政府采购应收融", "政穗保理服务", "receivable_finance",
       "政府采购应收账款保理", 300_000, 5_000_000, 60, 365, "5.200",
       "政府采购应收专项，信用风险低", _RCV, ["receivable"], ["receivable_invoice"], "1.0",
       ["企业持续经营满1年", "应收账款来自政府机关或事业单位", "采购合同需核验"]),
    _p("QIAN-V1-AR-04", "池式保理", "池穗金融服务", "receivable_finance",
       "应收账款池式循环保理", 500_000, 8_000_000, 90, 365, "5.800",
       "池式循环额度，应收账款可滚动置换", _RCV, ["receivable"], ["receivable_invoice"], "2.0",
       ["企业持续经营满2年", "应收账款来源须分散", "池内资产需定期报告"]),
    _p("QIAN-V1-AR-05", "明保理通", "明穗商业保理", "receivable_finance",
       "公开型应收账款保理", 200_000, 3_000_000, 30, 180, "6.000",
       "明保理模式，债务方已知晓", _RCV, ["receivable"], ["receivable_invoice", "delivery_receipt"], "1.0",
       ["企业持续经营满1年", "债务方须确认应收账款", "交货凭证需核验"]),
    _p("QIAN-V1-AR-06", "暗保理融", "隐穗金融服务", "receivable_finance",
       "隐蔽型应收账款保理", 300_000, 2_000_000, 30, 120, "6.800",
       "暗保理模式，利率较高", _RCV, ["receivable"], ["receivable_invoice"], "1.5",
       ["企业持续经营满1.5年", "应收账款须真实有效", "企业征信需良好"]),
    _p("QIAN-V1-AR-07", "反向保理", "核穗供应链金融", "receivable_finance",
       "核心企业发起的反向保理", 500_000, 10_000_000, 30, 270, "4.800",
       "核心企业信用传导，利率最优惠", _RCV, ["receivable"], ["receivable_invoice", "delivery_receipt"], "1.0",
       ["供应商持续经营满1年", "须为核心企业认证供应商", "核心企业须签署确认"]),
    _p("QIAN-V1-AR-08", "出口应收融", "海穗保理服务", "receivable_finance",
       "出口粮食应收账款融资", 500_000, 5_000_000, 60, 180, "5.900",
       "出口应收专项，支持外币账款", _RCV, ["receivable"], ["receivable_invoice", "delivery_receipt"], "2.0",
       ["企业持续经营满2年", "具有出口资质与报关单", "外汇账款需核验"]),
    _p("QIAN-V1-AR-09", "信保应收融", "信穗保险保理", "receivable_finance",
       "信用保险覆盖的应收保理", 300_000, 5_000_000, 30, 180, "5.500",
       "信用保险增信，利率较低", _RCV, ["receivable"], ["receivable_invoice"], "1.0",
       ["企业持续经营满1年", "应收账款须投保信用险", "保险单需核验"]),
    _p("QIAN-V1-AR-10", "线上保理通", "云穗数字保理", "receivable_finance",
       "全线上数字化保理融资", 100_000, 2_000_000, 15, 120, "6.500",
       "全线上操作，发票验真即放款", _RCV, ["receivable"], ["receivable_invoice"], "0.5",
       ["企业持续经营满半年", "发票须通过税务验真", "交易背景需线上核实"]),
]


def seed_finance_products(db: Session) -> None:
    for item in PRODUCTS:
        exists = db.scalar(
            select(FinanceProduct).where(FinanceProduct.product_code == item["product_code"])
        )
        if exists is None:
            db.add(FinanceProduct(**item))
    db.commit()
