import type { Partner, ReviewRecord, VerificationItem } from "./types";

export const partners: Partner[] = [
  {
    id: "P-G-021",
    name: "黑龙江北禾粮贸有限公司",
    type: "grain",
    typeLabel: "粮源供应方",
    sourceAgent: "粮小二",
    sourceTask: "东北玉米寻源任务 · XY-20260824-03",
    region: "黑龙江 · 绥化",
    business: "玉米、水稻收储与供应",
    updatedAt: "2026-08-24 10:36",
    verdict: "verify",
    summary: "基础经营信息与近期供货记录较完整，但本批次质检时间早于出库窗口，且集中交付能力尚未得到当前证据支持。建议补齐两项核验后继续接洽。",
    profile: [
      { label: "合作记录", value: "近 12 个月 4 次" },
      { label: "按期交付", value: "3 次按期，1 次晚 1 天" },
      { label: "本次供应量", value: "200 吨" },
      { label: "报价口径", value: "库内车板价 2,346 元/吨" },
    ],
    risks: [
      {
        id: "R-G-01",
        title: "质检报告与拟出库时间间隔较长",
        level: "medium",
        description: "现有质检日期为 8 月 12 日，拟出库窗口为 8 月 27—29 日，水分与容重可能发生变化。",
        evidence: "粮小二候选粮源 · 质检摘要",
        source: "粮小二",
        action: "要求装车前 48 小时内复检水分、容重与霉变粒。",
      },
      {
        id: "R-G-02",
        title: "集中交付能力待确认",
        level: "medium",
        description: "历史单次最大交付 120 吨，本次计划 200 吨在两天内完成装车。",
        evidence: "企业合作记录 · 历史交付摘要",
        source: "企业知识库",
        action: "确认每日装车能力，并提供两日发运排期。",
      },
      {
        id: "R-G-03",
        title: "报价未见明显偏离",
        level: "low",
        description: "当前报价处于同区域同等级候选粮源的合理区间内。",
        evidence: "粮小二候选对比 · 5 条区域报价",
        source: "粮小二",
        action: "按当前口径继续比价，无需额外处置。",
      },
    ],
  },
  {
    id: "P-L-008",
    name: "华北联运物流有限公司",
    type: "logistics",
    typeLabel: "物流服务方",
    sourceAgent: "运小二",
    sourceTask: "绥化—潍坊运输方案 · YS-20260824-02",
    region: "河北 · 石家庄",
    business: "粮食公铁联运与短驳服务",
    updatedAt: "2026-08-24 09:48",
    verdict: "proceed",
    summary: "承运范围覆盖本次线路，近期履约记录与运小二方案口径一致。换装节点已有明确预留时间，可继续询运，但仍需在发运前确认最终车皮计划。",
    profile: [
      { label: "合作记录", value: "近 12 个月 7 次" },
      { label: "准时到达", value: "6 次" },
      { label: "运输方式", value: "公路 + 铁路" },
      { label: "参考时效", value: "4—5 天" },
    ],
    risks: [
      {
        id: "R-L-01",
        title: "车皮计划需临近确认",
        level: "medium",
        description: "当前方案使用参考班列窗口，正式车皮计划需在发运前再次确认。",
        evidence: "运小二运输方案 · 发运窗口",
        source: "运小二",
        action: "询运时要求反馈确认时间与无法排车的替代安排。",
      },
      {
        id: "R-L-02",
        title: "近期履约表现稳定",
        level: "low",
        description: "近 7 次记录中无货损异常，1 次因天气晚到半天。",
        evidence: "企业合作记录 · 物流履约摘要",
        source: "企业知识库",
        action: "保留天气延误预留，无需暂停推进。",
      },
    ],
  },
  {
    id: "P-F-014",
    name: "融粮供应链服务",
    type: "finance",
    typeLabel: "资金服务方",
    sourceAgent: "钱小二",
    sourceTask: "采购周转资金匹配 · QP-20260824-01",
    region: "山东 · 济南",
    business: "粮食采购周转资金服务",
    updatedAt: "2026-08-24 11:02",
    verdict: "verify",
    summary: "额度、期限和用途与当前采购需求匹配，参考年化成本口径明确；服务费和提前结清费用仍需人工确认，建议取得完整费用说明后再决定。",
    profile: [
      { label: "匹配金额", value: "300,000 元" },
      { label: "使用期限", value: "45 天" },
      { label: "参考年化", value: "6.30%" },
      { label: "必要凭证", value: "采购订单、经营流水" },
    ],
    risks: [
      {
        id: "R-F-01",
        title: "部分费用口径待确认",
        level: "high",
        description: "当前产品资料仅提供参考年化成本，未列出服务费与提前结清费用。",
        evidence: "钱小二匹配结果 · 费用说明",
        source: "钱小二",
        action: "咨询时要求提供费用清单，并确认是否存在提前结清费用。",
      },
      {
        id: "R-F-02",
        title: "办理凭证尚未齐备",
        level: "medium",
        description: "采购订单已具备，最近 6 个月经营流水尚未确认。",
        evidence: "钱小二匹配结果 · 待确认条件",
        source: "钱小二",
        action: "确认经营流水是否满足办理要求。",
      },
    ],
  },
];

export const initialVerifications: VerificationItem[] = [
  {
    id: "V-081",
    partnerId: "P-G-021",
    partnerName: "黑龙江北禾粮贸有限公司",
    riskId: "R-G-01",
    title: "补充装车前复检报告",
    level: "medium",
    request: "复检水分、容重与霉变粒，检测时间应在装车前 48 小时内。",
    sourceAgent: "粮小二",
    status: "pending",
  },
  {
    id: "V-082",
    partnerId: "P-G-021",
    partnerName: "黑龙江北禾粮贸有限公司",
    riskId: "R-G-02",
    title: "确认两日集中发运排期",
    level: "medium",
    request: "提供每日计划装车量、车辆安排和异常替代方案。",
    sourceAgent: "粮小二",
    status: "pending",
  },
  {
    id: "V-079",
    partnerId: "P-L-008",
    partnerName: "华北联运物流有限公司",
    riskId: "R-L-01",
    title: "确认车皮计划反馈时间",
    level: "medium",
    request: "明确最终排车结果的反馈节点及公路替代安排。",
    sourceAgent: "运小二",
    status: "clear",
    note: "服务方承诺 8 月 25 日 18:00 前反馈，已提供公路备选。",
  },
  {
    id: "V-083",
    partnerId: "P-F-014",
    partnerName: "融粮供应链服务",
    riskId: "R-F-01",
    title: "取得完整费用说明",
    level: "high",
    request: "确认服务费、账户管理费及提前结清费用。",
    sourceAgent: "钱小二",
    status: "pending",
  },
];

export const reviewRecords: ReviewRecord[] = [
  {
    id: "AR-20260824-03",
    partnerId: "P-G-021",
    partnerName: "黑龙江北禾粮贸有限公司",
    typeLabel: "粮源供应方",
    date: "2026-08-24 10:36",
    verdict: "verify",
    summary: "质检时效与集中交付能力需要补充核验，其他基础信息未见明显异常。",
    riskCount: 2,
    experience: "该供应方历史小批量履约基本稳定；大于 150 吨的集中采购，应提前确认装车排期并要求临近装车复检。",
  },
  {
    id: "AR-20260822-06",
    partnerId: "P-L-008",
    partnerName: "华北联运物流有限公司",
    typeLabel: "物流服务方",
    date: "2026-08-22 16:20",
    verdict: "proceed",
    summary: "线路覆盖和近期履约稳定，车皮计划已补充确认，可继续询运。",
    riskCount: 1,
    experience: "该服务方公铁联运执行较稳定，但车皮排期通常在发运前 2—3 天最终确认，需同时保留公路替代方案。",
  },
  {
    id: "AR-20260820-02",
    partnerId: "P-F-014",
    partnerName: "融粮供应链服务",
    typeLabel: "资金服务方",
    date: "2026-08-20 14:08",
    verdict: "verify",
    summary: "基本办理条件匹配，费用说明仍有缺项，应在咨询阶段补齐。",
    riskCount: 1,
    experience: "使用该资金服务方产品时，除参考年化成本外，应单独确认服务费和提前结清费用。",
  },
];
